#!/bin/bash
apt update -y
apt install docker.io -y
idocker pull docker.elastic.co/elasticsearch/elasticsearch:7.6.2
docker run -it -p 9200:9200 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.6.2 bash
